apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-deployment
  namespace: monitoring
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: kibana:7.17.16
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 2000m
            memory: "2048Mi"
          requests:
            cpu: 500m
            memory: "1024Mi"
        env:
          - name: ELASTICSEARCH_HOSTS
            value: http://elasticsearch-client-0.elasticsearch-client:9200
          - name: ELASTICSEARCH_USERNAME
            value: kibana_system
          - name: ELASTICSEARCH_PASSWORD
            value: wMgDcYbjmUuQGgTDSpzf
          - name: SERVER_PUBLICBASEURL
            value: http://0.0.0.0:5601
          - name: XPACK_MONITORING_ENABLED
            value: "true"
          - name: XPACK_MONITORING_COLLECTION_ENABLED
            value: "true"
        ports:
        - containerPort: 5601
